export const SCREEN_ACCENT_COLORS = {
  PointOfSale: '#57d65a',
  Sales: '#4db7ff',
  Inventory: '#f7c843',
  Reports: '#8f7cff',
  ThirdParties: '#4db7ff',
  Products: '#ffb347',
  CashSessions: '#57d65a',
  Setup: '#ff6b7d',
  fallback: '#74a6ff',
};

export const HOME_BAR_THEME_COLORS = ['#6fd95f', '#58b8ff', '#f4c53d', '#71de6a', '#4ca7ff', '#f0b446', '#7bdc73'];

export const APP_THEME_COLORS = {
  light: {
    rootBackground: '#edf2fb',
    statusBarBackground: '#f7fbff',
    appBarBackground: '#f7fbff',
    appBarBorder: '#dbe7f7',
    brandOfir: '#1e63b7',
    brandOne: '#4ca53c',
    appBarTitle: '#47638b',
    iconButtonBackground: '#ffffff',
    iconButtonBorder: '#cfddf0',
    iconButtonIcon: '#235ea9',
    themeToggleIcon: '#1e3a8a',
    backButtonBackground: '#ffffff',
    backButtonBorder: '#cfddf0',
    backButtonIcon: '#334155',
    avatarBackground: '#ffffff',
    avatarBorder: '#c9d8eb',
    avatarText: '#1e3a8a',
    menuTriggerBackground: '#235ea9',
    menuTriggerBorder: '#1f4f8f',
    menuTriggerIcon: '#eff6ff',
  },
  dark: {
    rootBackground: '#060b16',
    statusBarBackground: '#0c1324',
    appBarBackground: '#0c1324',
    appBarBorder: '#1f2f4d',
    brandOfir: '#6fb7ff',
    brandOne: '#67cf52',
    appBarTitle: '#cad8f4',
    iconButtonBackground: '#111d34',
    iconButtonBorder: '#2e446e',
    iconButtonIcon: '#dbeafe',
    themeToggleIcon: '#f8cf59',
    backButtonBackground: '#121f37',
    backButtonBorder: '#314870',
    backButtonIcon: '#e2e8f0',
    avatarBackground: '#1e2f4d',
    avatarBorder: '#30486f',
    avatarText: '#dbeafe',
    menuTriggerBackground: '#1b4f95',
    menuTriggerBorder: '#3f78c6',
    menuTriggerIcon: '#eff6ff',
  },
  shared: {
    brandGlowTopDark: '#1d4ed8',
    brandGlowTopLight: '#60a5fa',
    brandGlowBottomDark: '#16a34a',
    brandGlowBottomLight: '#34d399',
    notificationBadgeBackground: '#dc2626',
    notificationBadgeText: '#ffffff',
    connectionOnlineBorder: '#2d8c47',
    connectionOnlineBackground: '#102d1c',
    connectionOfflineBorder: '#8f2a2a',
    connectionOfflineBackground: '#3f1111',
    connectionOnlineText: '#a7f3bd',
    connectionOfflineText: '#fecaca',
    connectionOnlineDot: '#57d65a',
    connectionOfflineDot: '#f87171',
  },
};

export const COMPONENT_THEME_COLORS = {
  shared: {
    placeholderText: '#64748b',
    modalOverlay: 'rgba(5,10,22,0.6)',
  },
  selectableField: {
    dark: {
      label: '#8ec5ff',
      triggerBorder: '#2d446a',
      triggerBackground: '#121f37',
      triggerText: '#dde9ff',
      chevron: '#8ec5ff',
      sheetBackground: '#0d172d',
      sheetBorder: '#29436a',
      title: '#e5eeff',
      inputBorder: '#2d446a',
      inputBackground: '#121f37',
      inputText: '#e5eeff',
      optionBorder: '#2d446a',
      optionBackground: '#121f37',
      optionText: '#d0dff9',
      emptyText: '#93a4b8',
      closeBtnBackground: '#1e63b7',
      closeBtnBorder: '#5ea9ff',
      closeBtnText: '#ffffff',
    },
    light: {
      label: '#235ea9',
      triggerBorder: '#cfddf0',
      triggerBackground: '#ffffff',
      triggerText: '#334155',
      chevron: '#235ea9',
      sheetBackground: '#f7fbff',
      sheetBorder: '#cfddf0',
      title: '#0f172a',
      inputBorder: '#cfddf0',
      inputBackground: '#ffffff',
      inputText: '#0f172a',
      optionBorder: '#cfddf0',
      optionBackground: '#ffffff',
      optionText: '#334155',
      emptyText: '#64748b',
      closeBtnBackground: '#1e63b7',
      closeBtnBorder: '#5ea9ff',
      closeBtnText: '#ffffff',
    },
    active: {
      singleBorder: '#5ab9ff',
      singleBackground: '#18304f',
      singleText: '#d9f0ff',
      multiBorder: '#57d65a',
      multiBackground: '#1b3825',
      multiText: '#e8ffe9',
    },
    clear: {
      dark: {
        background: '#13213a',
        border: '#395b87',
        text: '#e2e8f0',
      },
      light: {
        background: '#f7fbff',
        border: '#cfddf0',
        text: '#334155',
      },
    },
  },
  datePickerField: {
    dark: {
      webInputText: '#f8fafc',
      label: '#8ec5ff',
      fieldBorder: '#2d446a',
      fieldBackground: '#121f37',
      valueText: '#e5eeff',
      manualInputText: '#e5eeff',
      pickerBorder: '#2d446a',
      pickerBackground: '#0d172d',
    },
    light: {
      webInputText: '#0f172a',
      label: '#235ea9',
      fieldBorder: '#cfddf0',
      fieldBackground: '#ffffff',
      valueText: '#0f172a',
      manualInputText: '#0f172a',
      pickerBorder: '#cfddf0',
      pickerBackground: '#ffffff',
    },
  },
  paginatedList: {
    dark: {
      loadingIndicator: '#38bdf8',
      surfaceBorder: '#223a5e',
      surfaceBackground: '#0f182b',
      title: '#e2ecff',
      error: '#f87171',
      empty: '#94a3b8',
      meta: '#8aa2c9',
      pageBtnBorder: '#385b86',
      pageBtnBackground: '#13213a',
      pageBtnText: '#d9e8ff',
      pageText: '#94a3b8',
    },
    light: {
      containerBackground: '#edf2fb',
      surfaceBorder: '#d5e2f4',
      surfaceBackground: '#ffffff',
      title: '#0f172a',
      error: '#f87171',
      empty: '#475569',
      meta: '#334155',
      pageBtnBorder: '#cfddf0',
      pageBtnBackground: '#f7fbff',
      pageBtnText: '#334155',
      pageText: '#475569',
    },
  },
};
